language: python
python:
  - "3.8"

services:
  - postgresql

env:
  - DATABASE_URI=postgres://postgres:@localhost:5432/test

before_script:
  - psql -c 'create database test;' -U postgres
# command to install dependencies
install: "pip3 install -r requirements.txt"

script:
  - nosetests

#after_success:
#  - codecov
